<?php
/**
 * Controller is the customized base controller class.
 * All controller classes for this application should extend from this base class.
 */
class Controller extends CController
{
    /**
     * @param CAction $action
     */
    protected function afterAction($action)
    {
        header('Content-type: application/json');
        parent::afterAction($action); // TODO: Change the autogenerated stub
    }

}