<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Create menu category' => 'Создать категорию меню',
  'Delete menu category' => 'Удалить категорию меню',
  'ID' => 'ID',
  'List menu categories' => 'Список категорий меню',
  'Manage menu categories' => 'Управление категориями меню',
  'Menu categories' => 'Категории меню',
  'Parent ID' => 'ID родительской категории',
  'Place ID' => 'ID заведения',
  'Title' => 'Название',
  'Update menu category' => 'Редактировать категорию',
  'View menu category' => 'Просмотр категории',
    'Menu category' => 'Категория',
    'Update menu category' => 'Редактировать категорию',
);
