<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'ID' => 'ID',
  'Parent category ID' => 'ID родительской категории',
  'Place ID' => 'ID заведения',
  'Place' => 'Заведение',
  'Title' => 'Название',

    'List service cat' => 'Список категорий услуг',
    'List ServiceCat' => 'Список категорий',
    'Manage' => 'Управлять категориями',
    'Create service cat' => 'Создать категорию',
    'Create ServiceCat' => 'Создать категорию',
    'Manage Service Cats' => 'Управление категориями услуг',
    'View ServiceCat' => 'Просмотр категории',
    'Update ServiceCat' => 'Редактирование категории',
    'Delete ServiceCat' => 'Удалить категорию',

);
